"use client";
import { useState } from "react";
import data from "../lib/demo.json";
export default function Demo() {
  const [tab, setTab] = useState(0);
  const row = data.results[tab];
  return (
    <div className="demo">
      <div className="demo-header">
        <span className="pill">
          <span className="status-dot" /> RECORDED FIXTURE · NO LIVE TRADE
        </span>
        <div className="demo-tabs" aria-label="Research question">
          <button aria-pressed={tab === 0} onClick={() => setTab(0)}>
            Quick price check
          </button>
          <button aria-pressed={tab === 1} onClick={() => setTab(1)}>
            Investigate a trade
          </button>
        </div>
      </div>
      <div className="demo-grid">
        <div className="demo-story">
          <p className="eyebrow">YOU ASK / ETHUSDT</p>
          <h3>
            {tab === 0
              ? "“What is ETH doing?”"
              : "“Is there enough reason to buy ETH?”"}
          </h3>
          <p>
            {tab === 0
              ? "A price question needs a quote and a cross-check. Extra flow data would add cost without answering the question better."
              : "A trade question calls for more context. Telt adds recorded Smart Money flows to the independent price check."}
          </p>
          <div className="source-row">
            <span>Binance venue price</span>
            <span>FREE</span>
          </div>
          <div className="source-row">
            <span>CoinGecko quote</span>
            <span>$0.01</span>
          </div>
          <div className="source-row">
            <span>Nansen flow data</span>
            <span>{tab === 0 ? "SKIPPED" : "$0.05"}</span>
          </div>
          <div className="source-row">
            <strong>Fixture research cost</strong>
            <strong>$ {row.spent}</strong>
          </div>
          <p className="notice">
            {tab === 0
              ? "$0.05 of unnecessary flow research skipped in this fixture."
              : "More data adds context. It does not automatically justify an entry."}
          </p>
        </div>
        <div className="demo-result" aria-live="polite">
          <p className="eyebrow">THE DECISION</p>
          <h3>No trade is a result, too.</h3>
          <div className="decision-note">
            <strong>NO_TRADE</strong>
            <p>
              The fixture contains price and flow observations, but no tested
              entry rule. The scripted conclusion records that limitation and
              names what would require another decision.
            </p>
          </div>
          <div className="receipt">
            <details key={tab}>
              <summary>+ Inspect the actual research receipt</summary>
              <pre>{row.research}</pre>
            </details>
            <details key={tab + 2}>
              <summary>+ Inspect the stored decision</summary>
              <pre>{row.decision}</pre>
            </details>
          </div>
          <p className="notice">
            Generated by the product’s fixture runtime. The conclusion is
            scripted for this demo; no live model, payment, or order is
            represented here.
          </p>
        </div>
      </div>
      <div className="demo-foot">
        Reproduce locally with <code>npm run prove</code>. Compare both runs to
        see how the research question changes source selection.
      </div>
    </div>
  );
}
